### ISSUE TITLE
关于声卡驱动问题

### ISSUE THREAD

**Issue by liuran001** [lovelinessmoe/Lenovo_G400_Hackintosh#1]
您好，我使用您的 EFI 成功安装上了 11.6.6 系统，但声卡驱动方面还存在问题。
无论我使用 VoodooHDA 还是 AppleALC，驱动均能正常加载，但依旧无法检测到任何输出设备。我不知道是不是 11.6.6 的问题，想请问下您是否尝试安装过 11.6.6，声卡是否能正常驱动？
很久之前我使用 autersu 的 Clover EFI 安装 10.15，无论是 VoodooVDA 还是 AppleALC，都是可以正常工作的
另，我看到您在 README.md 中写到
```
4.OC版本使用的时候由于删除了OC注入的VooDooHDA，需手动移动到L/E文件夹中并重建缓存
```
请问下为什么不能直接使用OC进行注入，是因为这样无法生效吗？
我将 VoodooHDA 放到 L/E 下依旧无法正常工作

**Comment by lovelinessmoe** [comment]
10.15我也是能驱动的，安装了11后就不行了，通过oc的确实不能用，需要kext里的那个AppleHDADisabler.kext禁用AppleHDA后用voodoo驱动

**Comment by lovelinessmoe** [comment]
voodoo的官方里提到了这个11.3之后就不能正常用了

**Comment by lovelinessmoe** [comment]
https://www.insanelymac.com/forum/topic/314406-voodoohda-299/page/22/
